apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dc5q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dc5q
    app.kubernetes.io/part-of: ci1t-43256-0047-app
  name: devfile-sample-dc5q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dc5q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dc5q
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0047-tenant/ci1t-43256-0047-app/devfile-sample-dc5q@sha256:1314ab93064a74d2ee9bcb8e953e6d171ebfc5720da7a0f331a7272dee423c6b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
